### ISSUE TITLE
Sierpinski Triangle is TOO MUCH MATH

### ISSUE THREAD

**Issue by xwyzhx** [MakeSchool-Tutorials/Intro-Recursion-Trees-Swift-Playground#2]
We spent 5 hours figuring out the geometry behind the triangles and 5 minutes figuring out the logic. Maybe there could be another helper function to help calculate where the triangles have to be, or a more in depth explanation with equations of how to solve for the sides. PLEASE I HATE TRIANGLES NOW AND I DREAD HAVING TO EXPLAIN THIS TO MORE STUDENTS I AM DYINg

**Comment by dionlarson** [comment]
The hint has been updated from:

> The bottom two internal triangles have a base center that is horizontally offset by 1/4 of a _side_ from the original triangle's base canter. The top triangle has a base center 1/2 a _height_ above the original triangle's base center.

to:

> The bottom two internal triangles have a base center that is horizontally offset by 1/4 of a _side_ from the original triangle's base canter. The top triangle has a base center 1/2 a _height_ above the original triangle's base center. Since `drawTriangle` takes in a height, how are you going to calculate the side length? Maybe you should peek at the `drawTriangle` method for help…

I believe that 1/2 and 1/4 offsets should be within the skill set of students at this point. A 2-iteration Seirpinski does not take that long to test as you are tuning it.

It is okay for students to struggle a bit. Just have them reread the hint and write out the rules with pen and paper. From there, do the math by hand with `height = 100`. Translate that into code.

**NOTE:** Students who downloaded the playground more than 15 minutes ago will not see this updated hint... Give it to them in person / via slack.
